### ISSUE TITLE
docker question

### ISSUE THREAD

**Issue by Critter** [MikeBeas/switchblade#1]
oi mate. I've never mucked with node much, so I figured the docker container would be the easiest route to go. That said I've not fucked with docker other than following scripts for a pi. I figured I'd spin up a docker server on linode, but from that point I'm pretty much at a stand still. Anything you can point me in the right direction on?

btw. I was finally ignored on your website ◡̈

**Comment by MikeBeas** [comment]
Like I said in the README:

> Unfortunately, due to the wide variety of possible deployment platforms, it is impossible to provide specific directions for any particular deployment strategy or PAAS. There are many tutorials online that can help you get a Node application up and running on your favorite PAAS.

I haven't used Linode before, so unfortunately I couldn't provide too much direct help with that beyond linking to their docs and providing some general steps for Docker.

If you've just got Docker running but not deployed the image I believe you're at the step "Build a Docker Image from the Dockerfile" in this document: https://www.linode.com/docs/guides/docker-images-containers-and-dockerfiles-in-depth/

The Dockerfile from this repo is what you would need for that step. Since I haven't provided any pre-built images, you have to clone this Git repo to your Linode box and then run something like:

`docker run --name switchblade -d switchblade`

You'll also have to pass the run command your environment variables for your database connection, or use a .env file that you add to the repo's root level. The environment variables are defined in the README.

**Comment by Critter** [comment]
Cheers. I appreciate it. I think I was about halfway there. I'll let you know how it goes.

**Comment by Critter** [comment]
It's me again. ok. I scrapped the docker route and just spun up a node instance on linode. I'm at this point here...

![image](https://github.com/MikeBeas/switchblade/assets/73031/30c64d2e-0b2b-4f10-9925-55f1cb6bd2cd)

but I feel like an idiot as I can't figure out how to get to it in the browser. I've tried the ip:500, but no go..

I'm not sure what the fuck I'm doing wrong.  Any suggestions or ideas?

**Comment by MikeBeas** [comment]
I'm not sure how Linode handles this but on Heroku they automatically set a PORT environment variable, which causes the app to start on that port, and then they forward that port to port 80, the regular HTTP port.

If Linode does something similar you just need to point to the IP or domain name, not to a specific port.

If Linode isn't automatically handling port config for you that's the one thing you'll have to configure to make it reachable. You just have to figure out how to forward traffic coming into the Linode box on 80 (or 443 with SSL) to port 500.

You'll probably need to use Nginx for that if it's not already setup.

**Comment by MikeBeas** [comment]
I found this video which seems to have instructions for Nginx config at around the 34 minute mark if you need some Linode-specific instructions! https://youtu.be/sD8X4CApdpo

**Comment by Critter** [comment]
Cheers for that mate. I'll give it a shot here in a bit.

**Comment by Critter** [comment]
Whoot!! we have JSON output at initial GET! Thanks for your help

**Comment by MikeBeas** [comment]
Awesome! Glad to hear it's working!
